version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=simple_blog_api
   
    node-app:
        depends_on:
          - postgres
        image : docker.io/snehasharma2606/simpleblogapi
        ports:
           - "3000:3000"
        environment:
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=simple_blog_api
            - PGPASSWORD=postgres_password
            - PGPORT=5432